catalogobio/catalogo/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalogo'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^species_create/$',views.species_create, name='addspecies'),
    url(r'^species_view/$',views.species_view, name='viewspecies'),
    url(r'^species_list/$',views.species_list, name='listspecies'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^species_update/$',views.speciesUpdate, name='updateSpecies'),
    url(r'^user_update/$',views.userUpdate, name='userUpdate'),
    url(r'^user_update_action/$',views.updateInformation, name='userUpdateAction'),
    url(r'^signup/$',views.signup, name='signup'),
    url(r'^comment/$',views.addComment, name='comment'),
]

catalogobio/catalogobio/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/catalogo/', permanent=False), name='redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^catalogo/',include('catalogo.urls', namespace="images")),
]

catalogobio/catalogo/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models


CLASIFICATION_CHOICES = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
)

class UserProfile(models.Model):

   user = models.OneToOneField(User)
   country = models.CharField(max_length=256, blank=False, null=False)
   city = models.CharField(max_length=256, blank=False, null=False)
   interests = models.CharField(max_length=256, blank=False, null=False)

class Category(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)

    def __str__(self):
        return self.name

class Species(models.Model):
    name = models.CharField(max_length=256, blank=False, null=False)
    clasification = CLASIFICATION_CHOICES
    scientific_name = models.CharField(max_length=256, blank=False, null=False)
    category = models.ForeignKey(Category)
    picture = models.ImageField(upload_to='images', null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.scientific_name

class Comment(models.Model):
    species = models.ForeignKey(Species)
    email = models.CharField(max_length=256, blank=False, null=False)
    text = models.TextField(blank=True, null=True)

catalogobio/catalogo/forms.py
from .models import Species, User, Comment
from django.forms import ModelForm, TextInput


class SpeciesForm(ModelForm):

    class Meta:
        model = Species
        fields = [
            'name',
            'scientific_name',
            'category',
            'picture',
            'description',
            ]
class UserForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            ]


class CommentForm(ModelForm):
    READONLY_FIELDS = ('email')

    class Meta:
        model = Comment
        fields = [
            'email',
            'text',
        ]

catalogobio/catalogo/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.core import serializers
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from catalogobio import settings
from .models import Category
from .models import Species
from .models import Category
from .models import User
from .models import UserProfile
from .models import Comment
from .forms import SpeciesForm, UserForm, CommentForm

# Create your views here.


def index(request):
    category = request.GET.get('category')

    if request.user.is_authenticated():
        if category:
            species_list = Species.objects.filter(category=category)
        else:
            species_list = Species.objects.all()
        category_list = Category.objects.all()
        context = {
            'species_list': species_list,
            'category_list': category_list,
            'category': category,
        }
        return render(request, 'catalogo/index.html', context)
    else:
        return HttpResponseRedirect(reverse('catalogo:login'))


def species_list(request):
    category = request.GET.get('category')
    # import IPython; IPython.embed()
    if category:
        species_list = Species.objects.filter(category=category)
    else:
        species_list = Species.objects.all()
    category_list = Category.objects.all()
    context = {
        'species_list': species_list,
        'category_list': category_list,
        'category': category,
    }
    return render(request, 'catalogo/index_list.html', context)


def species_view(request):
    if request.method != 'GET':
        return HttpResponseRedirect(reverse('images:index'))

    id = request.GET.get('id')
    if not id:
        return HttpResponseRedirect(reverse('images:index'))

    species = Species.objects.get(id=id)
    categories = Category.objects.all()
    comments = Comment.objects.filter(species_id=id)
    context = {'species': species, 'categories': categories, 'comments': comments}
    return render(request, 'catalogo/species_view.html', context)


def species_create(request):
    if request.method == 'POST':
        form = SpeciesForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('images:index'))
    else:
        form = SpeciesForm()

    return render(request, 'catalogo/species_create.html', {'form': form})


def login_view(request):

    if request.user.is_authenticated():
        return redirect(reverse('catalogo:index'))

    message = ""

    if(request.method == 'POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('catalogo:index'))
        else:
            message = "Nombre de usuario o clave incorrecta"

    return render(request, 'catalogo/login.html', {'message': message})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("catalogo:index"))


def speciesUpdate(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        s_name = request.POST.get('s_name')
        category = Category.objects.get(name=request.POST.get('category'))
        description = request.POST.get('description')

        Species.objects.filter(id=request.POST.get('id')).update(name=name, scientific_name=s_name, category=category,
                                                                 description=description)

        return HttpResponse(True)

    else:
        return HttpResponse(False)


def userUpdate(request):
    if request.method == 'GET':
        if request.user.is_authenticated():
            current_user = User.objects.get(id=request.user.id)
            context = {'user': current_user}
            return render(request, 'catalogo/user_view.html', context)

        else:
            return HttpResponseRedirect(reverse('catalogo:login'))


def updateInformation(request):

    if request.method == 'GET':
        name = request.GET.get('name')
        last_name = request.GET.get('lname')
        username = request.GET.get('uname')

        country = request.GET.get('country')
        city = request.GET.get('city')
        interests = request.GET.get('interests')

        User.objects.filter(id=request.user.id).update(
            first_name=name, last_name=last_name, username=username)
        UserProfile.objects.filter(user_id=request.user.id).update(
            country=country, city=city, interests=interests)

        return HttpResponseRedirect(reverse('catalogo:index'))

@csrf_exempt
def signup(request):
    if request.method == 'POST':
        jsonUser = json.loads(request.body)

        username = jsonUser['username']
        first_name = jsonUser['first_name']
        last_name = jsonUser['last_name']
        email = jsonUser['email']
        password = jsonUser['password']

        user_model = User.objects.create_user(username=username, password=password)
        user_model.first_name = first_name
        user_model.last_name = last_name
        user_model.email = email
        user_model.save()

        last_user = User.objects.last()

        user_profile = UserProfile()
        user_profile.city = jsonUser['city']
        user_profile.country = jsonUser['country']
        user_profile.interests = jsonUser['interest']
        user_profile.user_id = last_user.id

        user_profile.save()

        subject = "Bienvenida"
        message = "Hola!/n Bienvenida monitora, Gracias por probar nuestra aplicacion"
        from_email = settings.EMAIL_HOST_USER
        to_list = [email, settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)

        return HttpResponse(serializers.serialize("json", [user_model, user_profile]))

    else:

        form = UserForm()
        return render(request, 'catalogo/signup.html', {'form': form})  # , 'profileform':profileform})


def addComment(request):
    if request.user.is_authenticated():

        form = CommentForm(request.POST)
        if request.method == 'GET':

            return render(request, 'catalogo/comment.html', {'form': form, 'id': request.GET.get('species_id')})

        else:
            if form.is_valid():

                comment_model = Comment()
                comment_model.email = request.POST.get('email')
                comment_model.text = request.POST.get('text')
                comment_model.species_id = request.GET.get('species_id')

                comment_model.save()

                response = redirect('catalogo:viewspecies')
                response['Location'] += '?id=' + request.GET.get('species_id')
                return response

            else:

                return render(request, 'catalogo/comment.html', {'form': form})

    else:
        return HttpResponseRedirect(reverse('catalogo:login'))

catalogobio/catalogo/templates/catalogo/comment.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add Comment</title>
</head>
<body>
<div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
    <div class="page-header"><h2>Comentario</h2></div>
    {% block content %}
    <form action="{% url 'catalogo:comment'%}?species_id={{id}}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <fieldset>
            <div class="form-group name">
                <label for="email" class="control-label">Email: </label>
                <input id="email" name="email" rows="8" cols="80" class="form-control" readonly value="{{ user.email }}">
            </div>
            <div class="form-group name">
                <label for="text" class="control-label">Commentario: </label>
                <textarea id="text" name="text" rows="8" cols="80" class="form-control"></textarea>
            </div>
        </fieldset>

        {% buttons %}
        <input type="submit" value="Agregar" class="btn btn-primary btn-block"/>
        <div class="form-group " style="margin-top: 10px">
            <input type=button value="Cancelar" onClick="javascript:history.go(-1);" class="btn btn-default btn-block">
        </div>
        {% endbuttons %}
    </form>
    {% endblock %}
</div>
</body>
</html>

catalogobio/catalogo/templates/catalogo/index.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script type="text/javascript">
      $(function(){
        function filter(value){
          var filter_list_url = "{% url 'catalogo:listspecies' %}?category=" + value;
          species_list = $("#species_list");
          species_list.load(filter_list_url);
        }

        var filter_ctrl = $("#category_filter");
        filter_ctrl.change(function(){
          filter(filter_ctrl.val());
        });
        filter(filter_ctrl.val());


      });
    </script>
    <meta charset="utf-8">
    <title>Índice</title>
  </head>
  <body>
    <div class="container">
        <br/>
      <div class="header clearfix">
        <nav>
            <ul class="nav nav-pills pull-left">
                <h2>Catalogo  de Biodiversidad</h2>
            </ul>
            <ul class="nav nav-pills pull-right">
                <li role="presentation" class="active"><a href="{% url 'catalogo:index' %}">Home</a></li>
                {% if user.is_authenticated %}

                <li role="presentation"><a class="glyphicon glyphicon-user" href="{% url 'catalogo:userUpdate' %}" >{{user.username }}</a></li>
                <li role="presentation"><a class="glyphicon glyphicon-log-out"
                                           href="{% url 'catalogo:logout' %}">Logout</a></li>
                {% else %}
                <li role="presentation"><a href="{% url 'catalogo:signup' %}">Registro</a></li>
                <li role="presentation"><a href="{% url 'catalogo:login' %}">Iniciar Sesion</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>

    <h3 class="text-center">Listado de Especies</h3>
    <div class="row">
      <a href="{% url 'images:addspecies' %}"
      class="btn btn-primary">
        <span class="glyphicon glyphicon-plus-sign">
        </span>
        Agregar Especie
      </a>
    </div>

    <div class="row" id="filter_div" align="center">
      <label for="category_filter">
        Categoría
      </label>
      <select id="category_filter"
        name="category_filter">
        <option value="" selected></option>
      {% for category in category_list %}
        <option value="{{category.id}}">
          {{category.name}}
        </option>
      {% endfor %}
      </select>

    </div>
    <br>
    <div class="row" id="species_list">
    </div>
  </body>
</html>

catalogobio/catalogo/templates/catalogo/index_list.html
<div class="row">
  {% for species in species_list %}
  <div class="col-md-4 col-sm-6 co-lg 3 well"
    align="center"
    style="width: 300; height: 300;
    margin-top: 5px;
    margin-left: 5px;
    margin-right: 5px;
    margin-bottom: 5px;
    background-color: light-gray;">
    <a href="species_view?id={{species.id}}">
      Ver Detalle Especie: {{species.name}}
    </a>
    <div style="
    width: 250; height: 250;
    background-image: url(/{{species.picture}});
    background-repeat: no-repeat;
    background-position: center;">
    </div>
    <!-- <img src="/{{species.picture}}"
      class="img-responsive"
      style="margin-top: 10px;
      margin-left: 10px;
      margin-right: 10px;
      margin-bottom: 10px;
      width: 80%; height: 80%;"> -->
  </div>
  {% endfor %}
</div>

catalogobio/catalogo/templates/catalogo/login.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Especie</title>
  </head>
  <body>
    {% block content %}
        <div class="row">
            <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
                <div class="page-header"><h2>Login</h2></div>
                {% if message %}
                    <div class="alert alert-danger">
                        {{message}}
                    </div>
                {% endif %}

                <form method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label" for="username">Nombre de usuario</label>
                        <input type="text" id="username" name="username" class="form-control" value="{{ username }}" placeholder="Nombre de usuario">
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control" value="{{ password }}" placeholder="Clave">
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Login</button>

                </form>
            </div>
        </div>
    {% endblock content %}
  </body>
</html>

catalogobio/catalogo/templates/catalogo/signup.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Especie</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"
                integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

        <!--<script src="/Users/cami7ord/Downloads/jquery-3.2.1.slim.min.js"></script>-->

        <script>

            function enviarForm() {

                var info = {username : $('#username').val(),
                            first_name: $('#first_name').val(),
                            last_name: $('#last_name').val(),
                            email: $('#email').val(),
                            password: $('#password').val(),
                            country: $('#country').val(),
                            city: $('#city').val(),
                            interest: $('#interest').val()
                            };

                $.ajax({
                    type: "POST",
                    url: "http://0.0.0.0:8000/catalogo/signup/",
                    data: JSON.stringify(info),
                    contentType: "application/json; charset=UTF-8",
                    dataType: "json",
                    success: function(data) {
                        window.location = "http://0.0.0.0:8000/catalogo/login/";
                    },
                    failure: function(error) {
                        alert("Hubo un error: " + error);
                    }
                });

                return false;
            }

        </script>

    </head>
    <body>
        <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
            <div class="page-header"><h2>Registro</h2></div>
            <form action="" method="post" onsubmit="return enviarForm();">
                <div class="form-group">
                    <label for="username" class="control-label">Nombre de usuario: </label>
                    <input id="username" type="text" name="username" value="" class="form-control"
                           placeholder="Nombre de usuario">
                </div>

                <div class="form-group">
                    <label for="first_name" class="control-label">Nombre: </label>
                    <input id="first_name" type="text" name="first_name" value="" class="form-control" placeholder="Nombre">
                </div>

                <div class="form-group">
                    <label for="last_name" class="control-label">Apellido: </label>
                    <input id="last_name" type="text" name="last_name" value="" class="form-control" placeholder="Apellido">
                </div>

                <div class="form-group">
                    <label for="email" class="control-label">Email: </label>
                    <input id="email" type="text" name="email" value="" class="form-control" placeholder="Email">
                </div>

                <div class="form-group">
                    <label for="password" class="control-label">Password: </label>
                    <input id="password" type="password" name="password" value="" class="form-control" placeholder="Contraseña">
                </div>

                <div class="form-group">
                    <label for="country" class="control-label">País: </label>
                    <input id="country" type="text" name="country" value="" class="form-control" placeholder="País">
                </div>

                <div class="form-group">
                    <label for="city" class="control-label">Ciudad: </label>
                    <input id="city" type="text" name="city" value="" class="form-control" placeholder="Ciudad">
                </div>

                <div class="form-group">
                    <label for="interest" class="control-label">Intereses: </label>
                    <input id="interest" type="text" name="interest" value="" class="form-control" placeholder="Intereses">
                </div>

                <input type="submit" value="Registrar" class="btn btn-primary btn-block"/>
                <a href="https://enigmatic-cove-30432.herokuapp.com/catalogo/" class="btn btn-default btn-block">Cancelar</a>

            </form>
        </div>
    </body>
</html>

catalogobio/catalogo/templates/catalogo/species_create.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Especie</title>
  </head>
  <body>
    <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
      <div class="page-header"><h2>Agregar especie</h2></div>
    {% block content %}
      <form action="{% url 'images:addspecies' %}"
      enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{form.as_p}} -->
        {% buttons %}
        <input type="submit" value="Add" class="btn btn-primary btn-block"/>
        {% endbuttons %}
      </form>
    {% endblock %}
    </div>
  </body>
</html>

catalogobio/catalogo/templates/catalogo/species_view.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Detalle | {{species.name}}</title>
</head>
<body>
<div id="container" class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
    <div id="update_label" class="alert alert-danger" style="display: none">
        <strong>Modifica la información necesaria. Clic en Guardar.</strong>
    </div>
    <div id="success_label" class="alert alert-success" style="display: none">
        <strong>Actualización realizada !</strong>
    </div>
    <form class="" action="{% url 'images:index' %}" method="get">
        <div class="form-group">
            <label for="name" class="control-label">Name: </label>
            <input id="name" type="text" name="name" value="{{species.name}}" class="form-control" readonly>
        </div>
        <div class="form-group scientific_name">
            <label for="scientific_name" class="control-label">Scientific Name: </label>
            <input id="s_name" type="text" name="scientific_name" value="{{species.scientific_name}}"
                   class="form-control" readonly>
        </div>
        <div class="form-group category">
            <label for="sel1">Category:</label>
            <select class="form-control" id="category" disabled>
                {% for category in categories %}
                {% if category.name == species.category.name %}
                <option selected>{{category.name}}</option>
                {% else %}
                <option>{{category.name}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="form-group picture">
            <label for="picture" class="control-label">Picture: </label>
            <img name="picture" src="/{{species.picture}}" class="img-responsive">
        </div>
        <div class="form-group name">
            <label for="description" class="control-label">Description: </label>
            <textarea id="description" name="description" rows="8" cols="80" class="form-control"
                      readonly>{{species.description}}</textarea>
        </div>

        <div class="form-group name">

            <label for="comments" class="control-label">Comentarios: </label>

            <ul class="list-group" style="margin-top: 10px">
                {%if comments %}
                    {% for comment in comments%}
                    <label for="comments" class="control-label" style="margin-top: 10px">{{comment.email}} : </label>
                    <textarea class="form-control" rows="3" readonly>{{comment.text}}</textarea>
                    {% endfor %}
                {% else %}
                <p style="text-align: center"><strong >No hay aún comentarios</strong></p>
                {% endif%}
            </ul>
        </div>

        <div class="form-group " style="display: none">
            <input id="update" onclick="enableUpdateSpecie()" value="Modificar" class="btn btn-warning btn-block">
        </div>

        <div class="form-group ">
            <a id="comment" href="{% url 'images:comment'%}?species_id={{species.id}}"
               class="btn btn-warning btn-block">Agregar Comentario</a>
        </div>

        <div class="form-group ">
            <input id="submit" type="submit" name="back" value="Volver Lista de Especies"
                   class="btn btn-primary btn-block">
        </div>

        <div class="form-group ">
            <input id="save" onclick="updateSpecie()" value="Guardar" class="btn btn-success btn-block"
                   style="display: none">
        </div>

        <div class="form-group ">
            <input id="cancel" type="submit" name="back" value="Cancelar" class="btn btn-primary btn-block"
                   style="display: none">
        </div>
    </form>

</div>

<!-- src="{{ STATIC_URL }}js/jquery-1.8.3.min.js"-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">

    function enableUpdateSpecie() {
        window.scroll(0, 0);
        document.getElementById('update_label').style.display = 'block';

        var elements = document.getElementsByTagName("input");
        var description = document.getElementById("description");
        var category = document.getElementById("category");

        for (var i = 0; i < elements.length; i++) {
            elements[i].removeAttribute('readonly');
        }
        description.removeAttribute('readonly');
        category.removeAttribute('disabled');

        document.getElementById('update').style.display = 'none';
        document.getElementById('submit').style.display = 'none';

        document.getElementById('save').style.display = 'block';
        document.getElementById('cancel').style.display = 'block';

    }

    function updateSpecie() {
        var name = document.getElementById('name').value
        var s_name = document.getElementById('s_name').value
        var category = $("#category :selected").text();
        var description = document.getElementById('description').value

        $.ajax({
            url: "{% url 'images:updateSpecies'%}",
            type: "POST",
            data: {
                "id": "{{species.id}}",
                "name": name,
                "s_name": s_name,
                "category": category,
                "description": description,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function (result) {
                if (result == 'True') {

                    var elements = document.getElementsByTagName("input");
                    var description = document.getElementById("description");
                    var category_element = document.getElementById("category");

                    for (var i = 0; i < elements.length; i++) {
                        elements[i].readOnly = true;
                    }

                    description.readOnly = true;
                    category_element.disabled = true;

                    document.getElementById('update').style.display = 'block';
                    document.getElementById('submit').style.display = 'block';

                    document.getElementById('save').style.display = 'none';
                    document.getElementById('cancel').style.display = 'none';

                    window.scroll(0, 0);
                    document.getElementById('update_label').style.display = 'none';
                    document.getElementById('success_label').style.display = 'block';

                    setTimeout(function () {
                        document.getElementById('success_label').style.display = 'none';
                    }, 2000);

                }
            },
            error: function (xhr) {
                alert('Ha Ocurrido un Error.');
            }
        });
    }

</script>

</body>
</html>

catalogobio/catalogo/templates/catalogo/user_view.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Detalle | {{species.name}}</title>
</head>
<body>

<div id="container" class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
        <h2 class="text-center">Actualizar Información</h2>

    <form class="" action="{% url 'images:userUpdateAction' %}" method="get">

        <div class="form-group">
            <label for="name" class="control-label">Name: </label>
            <input id="name" type="text" name="name" value="{{user.first_name}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name" class="control-label">Name: </label>
            <input id="lname" type="text" name="lname" value="{{user.last_name}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name" class="control-label">Name: </label>
            <input id="uname" type="text" name="uname" value="{{user.username}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name" class="control-label">Country: </label>
            <input id="country" type="text" name="country" value="{{user.userprofile.country}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name" class="control-label">City: </label>
            <input id="city" type="text" name="city" value="{{user.userprofile.city}}" class="form-control">
        </div>
        <div class="form-group">
            <label for="name" class="control-label">Interest: </label>
            <input id="interest" type="text" name="interests" value="{{user.userprofile.interests}}" class="form-control">
        </div>

       <!-- <div class="form-group picture">
            <label for="picture" class="control-label">Picture: </label>
            <img name="picture" src="/{{species.picture}}" class="img-responsive">
        </div>-->

        <div class="form-group ">
            <input id="submit" type="submit"  value="Actualizar Información"
                   class="btn btn-primary btn-block">
        </div>
        <div class="form-group ">
            <input type="submit" name="back" value="Regresar"
                   class="btn btn-default btn-block">
        </div>

    </form>

</div>


</body>
</html>